// <auto-generated />
using System;
using FormFiller.Infrasctructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FormFiller.Infrasctructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251119174912_params")]
    partial class @params
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FormFiller.Domain.Entities.Generator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Generators");
                });

            modelBuilder.Entity("FormFiller.Domain.Entities.Param", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GeneratorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GeneratorId");

                    b.ToTable("Params");
                });

            modelBuilder.Entity("FormFiller.Domain.Entities.Schema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Schemas");
                });

            modelBuilder.Entity("FormFiller.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GeneratorSchema", b =>
                {
                    b.Property<Guid>("GeneratorsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SchemasId")
                        .HasColumnType("uuid");

                    b.HasKey("GeneratorsId", "SchemasId");

                    b.HasIndex("SchemasId");

                    b.ToTable("GeneratorSchema");
                });

            modelBuilder.Entity("FormFiller.Domain.Entities.Param", b =>
                {
                    b.HasOne("FormFiller.Domain.Entities.Generator", "Generator")
                        .WithMany("Params")
                        .HasForeignKey("GeneratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generator");
                });

            modelBuilder.Entity("FormFiller.Domain.Entities.Schema", b =>
                {
                    b.HasOne("FormFiller.Domain.Entities.User", null)
                        .WithMany("Schemas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeneratorSchema", b =>
                {
                    b.HasOne("FormFiller.Domain.Entities.Generator", null)
                        .WithMany()
                        .HasForeignKey("GeneratorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormFiller.Domain.Entities.Schema", null)
                        .WithMany()
                        .HasForeignKey("SchemasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormFiller.Domain.Entities.Generator", b =>
                {
                    b.Navigation("Params");
                });

            modelBuilder.Entity("FormFiller.Domain.Entities.User", b =>
                {
                    b.Navigation("Schemas");
                });
#pragma warning restore 612, 618
        }
    }
}
